// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvFqz-wTHOk9PGb79h9E8OHwMMZl13L_M',
    appId: '1:974745779266:web:0f7a2af63e0937c8d0c1db',
    messagingSenderId: '974745779266',
    projectId: 'crud-test-1db1c',
    authDomain: 'crud-test-1db1c.firebaseapp.com',
    storageBucket: 'crud-test-1db1c.appspot.com',
    measurementId: 'G-LCR5H6JDYR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-BNDjwebiJzBnBeeaE2APzMx9tVPSfDY',
    appId: '1:974745779266:android:493fffe3b3e16bfed0c1db',
    messagingSenderId: '974745779266',
    projectId: 'crud-test-1db1c',
    storageBucket: 'crud-test-1db1c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiKCzDq_dr3WACAyfe9csKO-aGP7HTzPI',
    appId: '1:974745779266:ios:3fc28abf0e129ad0d0c1db',
    messagingSenderId: '974745779266',
    projectId: 'crud-test-1db1c',
    storageBucket: 'crud-test-1db1c.appspot.com',
    iosClientId: '974745779266-5g8dkv01t0u60hf3hbec8407cfd9dbhk.apps.googleusercontent.com',
    iosBundleId: 'com.example.crudproyecto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiKCzDq_dr3WACAyfe9csKO-aGP7HTzPI',
    appId: '1:974745779266:ios:ca99a31b6ca4848cd0c1db',
    messagingSenderId: '974745779266',
    projectId: 'crud-test-1db1c',
    storageBucket: 'crud-test-1db1c.appspot.com',
    iosClientId: '974745779266-t15r6g53m66l8bqovqbr6dkuu17e0o9u.apps.googleusercontent.com',
    iosBundleId: 'com.example.crudproyecto.RunnerTests',
  );
}
